const app = document.getElementById('app');
let db=null,currentUser=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function shell(c){app.innerHTML=`<main class="layout"><header class="topbar"><strong>Loan Appraise V3</strong><span>${esc(currentUser?.email)}</span><button id="logout" class="secondary">Logout</button></header><div class="content">${c}</div></main>`;document.getElementById('logout').onclick=async()=>{await db.auth.signOut();location.reload()};}
function err(m){app.innerHTML=`<main class="auth"><section class="card"><h1>Loan Appraise V3</h1><p>${esc(m)}</p><button class="secondary" onclick="location.reload()">Refresh</button></section></main>`}
async function login(){app.innerHTML=`<main class="auth"><section class="card"><h1>Loan Appraise V3</h1><p>Secure loan appraisal and approval.</p><label>Email<input id="email" type="email"></label><label>Password<input id="password" type="password"></label><button class="primary" id="signin">Sign In</button><p id="msg"></p></section></main>`;document.getElementById('signin').onclick=async()=>{let m=document.getElementById('msg'),email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||!password){m.textContent='Email and password are required.';return}m.textContent='Signing in...';let{error}=await db.auth.signInWithPassword({email,password});if(error){m.textContent=error.message;return}location.reload()}}
async function dashboard(){shell(`<section class="hero"><div><h1>Loan Officer Dashboard</h1><p>Manage loan applications.</p></div><button id="newApp" class="primary">＋ New Application</button></section><section class="cards"><div class="stat"><span>Drafts</span><strong>0</strong></div><div class="stat"><span>Submitted</span><strong>0</strong></div><div class="stat"><span>Returned</span><strong>0</strong></div><div class="stat"><span>Pending Approval</span><strong>0</strong></div></section><section class="panel"><h2>Applications</h2><p>No applications yet. Start a new application.</p></section>`);document.getElementById('newApp').onclick=()=>customerStep()}
function customerStep(){shell(`<div class="stephead"><div><small>Step 1 of 8</small><h1>Customer Information</h1></div><span class="badge">Draft</span></div><div class="steps"><b>1 Customer</b><span>2 Loan Request</span><span>3 Business & Sales</span><span>4 Financials</span><span>5 Products</span><span>6 Balance Sheet</span><span>7 Collateral</span><span>8 Review</span></div><section class="panel formgrid"><label>Full Name<input id="full_name"></label><label>Phone Number<input id="phone"></label><label>NIN<input id="nin"></label><label>BVN<input id="bvn"></label><div class="actions wide"><button id="back" class="secondary">Back</button><button id="saveCustomer" class="primary">Save & Continue</button></div><p id="saveMsg" class="wide"></p></section>`);document.getElementById('back').onclick=dashboard;document.getElementById('saveCustomer').onclick=async()=>{let msg=document.getElementById('saveMsg'),full_name=document.getElementById('full_name').value.trim();if(!full_name){msg.textContent='Full name is required.';return}msg.textContent='Saving customer...';const payload={full_name,phone:document.getElementById('phone').value.trim()||null,nin:document.getElementById('nin').value.trim()||null,bvn:document.getElementById('bvn').value.trim()||null};const{data,error}=await db.from('customers').insert(payload).select().single();if(error){msg.textContent='Could not save: '+error.message;return}loanRequestStep(data.id)}}
function loanRequestStep(customerId){shell(`<div class="stephead"><div><small>Step 2 of 8</small><h1>Loan Request</h1></div></div><div class="steps"><span>1 Customer</span><b>2 Loan Request</b><span>3 Business & Sales</span><span>4 Financials</span><span>5 Products</span><span>6 Balance Sheet</span><span>7 Collateral</span><span>8 Review</span></div><section class="panel formgrid"><label>Loan Amount (₦)<input id="amount" type="number" min="1"></label><label>Tenor (months)<input id="tenor" type="number" min="1"></label><label>Purpose<input id="purpose"></label><div class="actions wide"><button id="back" class="secondary">Back</button><button id="saveLoan" class="primary">Save & Continue</button></div><p id="saveMsg" class="wide"></p></section>`);document.getElementById('back').onclick=customerStep;document.getElementById('saveLoan').onclick=async()=>{let msg=document.getElementById('saveMsg'),amount=Number(document.getElementById('amount').value),tenure=Number(document.getElementById('tenor').value);if(!amount||!tenure){msg.textContent='Loan amount and tenor are required.';return}msg.textContent='Saving loan request...';const payload={customer_id:customerId,amount,tenure,purpose:document.getElementById('purpose').value.trim()||null,status:'draft',created_by:currentUser.id};const{error}=await db.from('loan_applications').insert(payload).select().single();if(error){msg.textContent='Could not save: '+error.message;return}businessStep()}}
function businessStep(){shell(`<div class="stephead"><small>Step 3 of 8</small><h1>Business & Sales</h1></div><section class="panel"><p>Business & Sales worksheet.</p><button class="primary" onclick="financialsStep()">Save & Continue</button></section>`)}
function financialsStep(){shell(`<div class="stephead"><small>Step 4 of 8</small><h1>Financials</h1></div><section class="panel"><p>Financials worksheet.</p><button class="primary" onclick="productsStep()">Save & Continue</button></section>`)}
function productsStep(){shell(`<div class="stephead"><small>Step 5 of 8</small><h1>Products / Trading Lines</h1></div><section class="panel"><p>Products worksheet.</p><button class="primary" onclick="balanceSheetStep()">Save & Continue</button></section>`)}
function balanceSheetStep(){shell(`<div class="stephead"><small>Step 6 of 8</small><h1>Balance Sheet</h1></div><section class="panel"><p>Balance Sheet worksheet.</p><button class="primary" onclick="collateralStep()">Save & Continue</button></section>`)}
function collateralStep(){shell(`<div class="stephead"><small>Step 7 of 8</small><h1>Collateral</h1></div><section class="panel"><p>Collateral worksheet.</p><button class="primary" onclick="reviewStep()">Save & Continue</button></section>`)}
function reviewStep(){shell(`<div class="stephead"><small>Step 8 of 8</small><h1>Review</h1></div><section class="panel"><p>Application review and submission.</p><button class="primary">Submit for Supervisor Review</button></section>`)}
async function init(){try{if(!window.SUPABASE_URL||!window.SUPABASE_PUBLISHABLE_KEY)return err('Supabase configuration is missing.');if(!window.supabase?.createClient)return err('The secure database library did not load.');db=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);const{data,error}=await db.auth.getSession();if(error)return err(error.message);if(!data.session)return login();currentUser=data.session.user;await dashboard()}catch(e){err(e.message||String(e))}}
window.customerStep=customerStep;window.loanRequestStep=loanRequestStep;window.financialsStep=financialsStep;window.productsStep=productsStep;window.balanceSheetStep=balanceSheetStep;window.collateralStep=collateralStep;window.reviewStep=reviewStep;init();
